### ISSUE TITLE
Case insensitive tags

### ISSUE THREAD

**Issue by Alteras1** [RpNation/BBCode#6]
BBob doesn't seem to support case insensitive tags. Might need to make suggestion/open PR on BBob's repo. Could also consider removing the allowed tags mode and do a custom bbob plugin to walk the tree similar to how we already do with newlines.

**Comment by Rhababo** [comment]
Could we just .toLowerCase() anything entered in brackets? 

Example: [cOLor=BLUe] -> [color=blue]

**Comment by Rhababo** [comment]
So just like you said, the allowed tags mode is what's causing the issue. 
```
 * @private
       * @param {String} value
       * @return {boolean}
       */ const isAllowedTag = (value)=>{
            if (options.onlyAllowTags && options.onlyAllowTags.length) {
                return options.onlyAllowTags.indexOf(value) >= 0;
            }
            return true;
        };
```
Because the toTagNode() function already has a .toLowerCase in it
```
toTagNode() {
            return new TagNode(this.tag.toLowerCase(), this.attrs, this.content);
        }
```

So adding .toLowerCase() here: 
```
  if (options.onlyAllowTags && options.onlyAllowTags.length) {
      return options.onlyAllowTags.indexOf(value.**toLowerCase()**) >= 0;
  }
```

Gives us the right output.

<img width="400" alt="Screenshot 2023-09-25 at 9 02 21 PM" src="https://github.com/RpNation/BBCode/assets/137821920/06c956ef-254c-42fe-97ab-9c211a50c6ff">


---

So we could either, copy the entire parser code from bbob, change this line, and import it as an option during the bbob call. Or we could, as you said, make a suggestion on the bbob repo.

**Comment by Rhababo** [comment]
I went ahead and opened an issue on the BBob GitHub. 
https://github.com/JiLiZART/BBob/issues/190#issue-1912564626

**Comment by Mondrethos** [comment]
> I went ahead and opened an issue on the BBob GitHub. [JiLiZART/BBob#190 (comment)](https://github.com/JiLiZART/BBob/issues/190#issue-1912564626)

It seems like its going to get fixed on BBob, pretty hype.

**Comment by Mondrethos** [comment]
The fix has been merged into BBob
