### ISSUE TITLE
Update BBCode to style with theme.

### ISSUE THREAD

**Issue by kyuukestu** [RpNation/bbcode#63]
The styles for the BBcodes need to be updated to use the variables set in the theme.

**Comment by Mondrethos** [comment]
Hi theme person here.

What do we need exactly? In the main theme I have only two variable colors. I don't completely understand the way the plugin works (yet), but I can provide as many color approvals, variables and such as needed. I can start with the light and dark colors for backgrounds that may be needed by some BBCodes if desired.

**Comment by MShultz** [comment]
@Mondrethos  This issue is just documenting that we need to update the plugin's style to use the theme variables so they dynamically adjust to dark/light/other modes. Currently, you can see the issue if you create a spoiler tag using dark mode and open it up. The background is white by default, which is fine, except the font color for dark mode is also light, which makes text unreadable.
